= python basics

= assignment 1


+*In[1]:*+
[source, ipython3]
----
year=int(input("enter the year for zodiacsign"))
if year%12==0:
    print("Monkey")
elif year%12==1:
    print("Rooster")
elif year%12==2:
    print("Dog")
elif year%12==3:
    print("pig")
elif year%12==4:
    print("Rat")
elif year%12==5:
    print("ox")
elif year%12==6:
    print("Tiger")
elif year%12==7:
    print("Rabbit")
elif year%12==8:
    print("Dragon")
elif year%12==9:
    print("Snake")
elif year%12==10:
    print("Horse")
else:
    print("Sheep")
----


+*Out[1]:*+
----
enter the year for zodiacsign2000
Dragon
----


+*In[3]:*+
[source, ipython3]
----
'distance covered with cost'
dist=int(input('enter distance:'))
wt=int(input('enter weight:'))
if dist>=500:
    if wt>=100:
        cost=5*dist
    elif wt>=10 and wt<100:
            cost=6*dist
    else:
        cost=7*dist
else:
    if wt>=100:
        cost=8*dist
    else:
        cost=5*dist
        print('charge of cost:',cost)    
----


+*Out[3]:*+
----
enter distance:45
enter weight:25
charge of cost: 225
----


+*In[14]:*+
[source, ipython3]
----
' printing the cost of ticket'
s=625
c=750
up=850
b=100
x=int(input('type of seat:'))
print('do you pay through cash or card')
y=str(input('payment mode:'))
while y=='card':
    z=x*5/100
    cost=x-z
    print('cost of ticket:',cost)
else:    
    if y=='cash':
        w=x*10/100
        cost=x-w
        print('cost of ticket:',cost)
----


+*Out[14]:*+
----
type of seat:850
do you pay through cash or card
payment mode:cash
cost of ticket: 765.0
----


+*In[23]:*+
[source, ipython3]
----
'required energy '
I=int(input('initial temperature:'))
f=int(input('final temperature:'))
m=int(input('water in kg:'))
q=m*(f-I)*4184
print(q)
----


+*Out[23]:*+
----
initial temperature:45
final temperature:78
water in kg:15
2071080
----


+*In[9]:*+
[source, ipython3]
----

user=str(input('enter month'))
if user==december or january or febraury:
    print('winter')
elif user==march or april or may:
    print('spring')
elif user==june or july or aug:
    print('summer')
else:
    print('autum')
----


+*Out[9]:*+
----
enter monthmay


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-9-d1bc33729f14> in <module>
          1 user=str(input('enter month'))
    ----> 2 if user==december or january or febraury:
          3     print('winter')
          4 elif user==march or april or may:
          5     print('spring')
    

    NameError: name 'december' is not defined

----


+*In[13]:*+
[source, ipython3]
----
M=int(input('enter month number:'))
def findseason (M) : 
      
    # Taken all the possible 
    # month numbers in the list. 
    list1 = [[12 , 1 , 2], [3 , 4 , 5],  
             [6 , 7 , 8], [9 , 10 , 11]] 
               
    # Matching the month number 
    # with the above list entries  
    if M in list1[0] : 
        print ( "WINTER" ) 
    elif M in list1[1] : 
        print ( "SPRING" ) 
    elif M in list1[2] : 
        print ( "SUMMER" ) 
    elif M in list1[3] : 
        print ( "AUTUMN" ) 
    else : 
        print ( "Invalid Month Number" ) 
   
#M = 5
findseason ( M ) 
  
#M = 10
#print("For Month number:", M); 
#findseason ( M ) 
----


+*Out[13]:*+
----
enter month number:10
AUTUMN
----


+*In[49]:*+
[source, ipython3]
----
'bmi'
u_wt=int(input('enter your weight in pounds:'))
u_ht=int(input('enter your height in inches:'))
wt_kg=0.4535*u_wt
ht_mt=0.0254*u_ht
BMI=wt_kg/(ht_mt)*(ht_mt)
BMI
if BMI<18.5:
    print('under weight')
elif 18.5<=BMI<25.0:
    print('Normal')
elif 25.0<=BMI<30.0:
    print('over weight')
elif 30.0<=BMI:
    print('obesity')
----


+*Out[49]:*+
----
enter your weight in pounds:60
enter your height in inches:49
over weight
----


+*In[3]:*+
[source, ipython3]
----
'sum of the digit'
num=int(input('enter the number between 100 and 1000:'))
rem=0
sumdigit=0
if num>100 and num<=1000:
    while num>0:
        rem=num%10
        sumdigit=sumdigit+rem
        num=num//10
    print(sumdigit)
----


+*Out[3]:*+
----
enter the number between 100 and 1000:456
15
----


+*In[57]:*+
[source, ipython3]
----
'palindrome between 1 to 1000'
max=int(input('enter the max value:'))
min=int(input('enter the min value'))
print('palindrome numbers bbetween %d and %d are:',(min,max))
for num in range (min,max+1):
    temp=num
    rev=0
    while temp>0:
        rem=temp%10
        rev=(rev*10)+rem
        temp=temp//10
    if num==rev:
        print('%d'%num,end=' ')
----


+*Out[57]:*+
----
enter the max value:1000
enter the min value1
palindrome numbers bbetween %d and %d are: (1, 1000)
1 2 3 4 5 6 7 8 9 11 22 33 44 55 66 77 88 99 101 111 121 131 141 151 161 171 181 191 202 212 222 232 242 252 262 272 282 292 303 313 323 333 343 353 363 373 383 393 404 414 424 434 444 454 464 474 484 494 505 515 525 535 545 555 565 575 585 595 606 616 626 636 646 656 666 676 686 696 707 717 727 737 747 757 767 777 787 797 808 818 828 838 848 858 868 878 888 898 909 919 929 939 949 959 969 979 989 999 ----


+*In[1]:*+
[source, ipython3]
----
'Armstrong numbers between 1 to 1000'
min=int(input('enter lower range:'))
max=int(input('enter upper range'))
for num in range(min,max+1):
    sum=0
    temp=num
    while temp>0:
        digit=temp%10
        sum+=digit**3
        temp//=10
    if num==sum:
        print(num)
----


+*Out[1]:*+
----
enter lower range:1
enter upper range1000
1
153
370
371
407
----


+*In[16]:*+
[source, ipython3]
----
for fizzbuzz in range(100):  
  
    # number divisible by 3, print 'Fizz'  
    # in place of the number 
    if fizzbuzz % 15 == 0:  
        print("FizzBuzz")                                          
        continue
  
    # number divisible by 5, print 'Buzz' 
    # in place of the number 
    elif fizzbuzz % 3 == 0:      
        print("Fizz")                                          
        continue
  
    # number divisible by 15 (divisible  
    # by both 3 & 5), print 'FizzBuzz' in 
    # place of the number 
    elif fizzbuzz % 5 == 0:          
        print("Buzz")                                      
        continue
  
    # print numbers 
    print(fizzbuzz) 
----


+*Out[16]:*+
----
FizzBuzz
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
----


+*In[8]:*+
[source, ipython3]
----
h=int(input('enter height of well:'))
u=int(input('enter meters he climbs in each step:'))
d=int(input('enter meters slips down each step:'))
if d>=u and h>u:
        print("-1")
elif h<=u:
    print("1")
else:
    ans=(h-u)//(u-d)
    ans=ans+2
print(ans)
----


+*Out[8]:*+
----
enter height of well:200
enter meters he climbs in each step:50
enter meters slips down each step:1
5
----


+*In[ ]:*+
[source, ipython3]
----

----
